### ISSUE TITLE
'Can't read Kafka version from MANIFEST.MF' warning in the logs - 0.8

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-kafka#1]
Seeing this warning in the logs for 0.8 Kafka client:

```
Can't read Kafka version from MANIFEST.MF. Possible cause: java.lang.NullPointerException
```

Related to fat jar packaging per https://qnalist.com/questions/5832650/warning-on-startup-of-consumer-app-with-0-8-2-rc2 and https://issues.apache.org/jira/browse/KAFKA-1901 Looks benign, and not an issue on 0.9.

**Comment by Lhfcws** [comment]
I've met with this problem in Kafka 0.9

**Comment by andrus** [comment]
@Lhfcws  Interesting. I haven't seen it anymore on 0.9. Are you using bootique-kafka-client?

**Comment by andrus** [comment]
Won't fix. No longer supporting Kafka 0.8
