### ISSUE TITLE
Update Kafka clients and streams version

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-kafka#33]
Bootique is using version `2.7.2` of Kafka dependencies that is couple years old as of reporting this.

For instance current Kafka Streams docs are referring to the methods that are not even there, so it would be great if we update it.

**Comment by andrus** [comment]
Good catch. Please go ahead with the upgrade

**Comment by stariy95** [comment]
Kafka dependencies upgraded to `3.4.0`
